
export const ADD_QUESTION_REQUESTED = 'ADD_QUESTION_REQUESTED'
export const ADD_QUESTION_LOADED = 'ADD_QUESTION_LOADED'
export const ADD_QUESTION_FAILED = 'ADD_QUESTION_FAILED'

export const GET_QUESTIONS_REQUESTED = 'GET_QUESTIONS_REQUESTED'
export const GET_QUESTIONS_LOADED = 'GET_QUESTIONS_LOADED'
export const GET_QUESTIONS_FAILED = 'GET_QUESTIONS_FAILED'

export const START_GAME_LOADED = 'START_GAME_LOADED'
export const CORRECT_ANSWER = 'CORRECT_ANSWER'
export const WRONG_ANSWER = 'WRONG_ANSWER'
export const GAME_OVER = 'GAME_OVER'
export const ADD_ID_QUESTION = 'ADD_ID_QUESTION'
export const QUESTION_TOUCHED = 'QUESTION_TOUCHED'
export const TIME_IS_UP = 'TIME_IS_UP'
export const HINT_ACTIVATED = 'HINT_ACTIVATED'


export const ADD_RECORD_REQUESTED = 'ADD_RECORD_REQUESTED'
export const ADD_RECORD_LOADED = 'ADD_RECORD_LOADED'
export const ADD_RECORD_FAILED = 'ADD_RECORD_FAILED'

